[package]
name = "shadcn-ui-leptos-button"
description = "Leptos port of shadcn/ui button."
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
tailwind_fuse.workspace = true
